# gemini_service.py
import os
import json
import re
import google.generativeai as genai
from dotenv import load_dotenv
from prompts import BRD_SYSTEM_INSTRUCTION, BRD_PROMPT_TEMPLATE

# Load environment variables
load_dotenv()

# Retrieve API Key
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# Configure genai SDK if API key exists
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)

def generate_erp_requirements(project_name: str, industry: str, features: list, scope_details: str, creativity_level: float) -> dict:
    """
    Calls the Gemini API to generate all 8 ERP specification sections inside a structured JSON response.
    
    Args:
        project_name (str): Name of the target ERP project.
        industry (str): Industry domain (e.g. FinTech, Healthcare).
        features (list): Selected core module names.
        scope_details (str): User-provided scope and context details.
        creativity_level (float): A value from 0.0 to 1.0 mapping to API temperature.
        
    Returns:
        dict: Parsed dictionary with keys: brd, srs, use_cases, user_stories, database_design, kpis, workflow, reports.
    """
    if not GEMINI_API_KEY:
        raise ValueError("GEMINI_API_KEY is not configured. Please define it in your .env file.")
        
    # Format the prompt
    features_str = ", ".join(features) if features else "None selected"
    prompt = BRD_PROMPT_TEMPLATE.format(
        project_name=project_name,
        industry=industry,
        features=features_str,
        scope_details=scope_details,
        creativity_level=creativity_level
    )
    
    generation_config = genai.types.GenerationConfig(
        temperature=float(creativity_level),
        max_output_tokens=8192,
        response_mime_type="application/json",
        response_schema={
            "type": "OBJECT",
            "properties": {
                "brd": {"type": "STRING"},
                "srs": {"type": "STRING"},
                "use_cases": {"type": "STRING"},
                "user_stories": {"type": "STRING"},
                "database_design": {"type": "STRING"},
                "kpis": {"type": "STRING"},
                "workflow": {"type": "STRING"},
                "reports": {"type": "STRING"},
            },
            "required": ["brd", "srs", "use_cases", "user_stories", "database_design", "kpis", "workflow", "reports"],
        }
    )
    
    try:
        # Initialize the model with system instruction
        model = genai.GenerativeModel(
            model_name="gemini-2.5-flash",
            generation_config=generation_config,
            system_instruction=BRD_SYSTEM_INSTRUCTION
        )
        
        # Call the API
        response = model.generate_content(prompt)
        
        if not response.text:
            raise RuntimeError("Gemini API returned an empty response.")
            
        # Clean response string if it has markdown JSON wrappers
        cleaned_text = response.text.strip()
        if cleaned_text.startswith("```json"):
            cleaned_text = cleaned_text[7:]
        if cleaned_text.endswith("```"):
            cleaned_text = cleaned_text[:-3]
        cleaned_text = cleaned_text.strip()
        
        # Parse JSON
        parsed_data = json.loads(cleaned_text)
        
        # Ensure all required keys exist, fill with empty markdown if missing
        required_keys = ["brd", "srs", "use_cases", "user_stories", "database_design", "kpis", "workflow", "reports"]
        for key in required_keys:
            if key not in parsed_data:
                parsed_data[key] = f"*Section {key} was not generated by AI.*"
                
        return parsed_data
        
    except json.JSONDecodeError as je:
        raise RuntimeError(f"Failed to parse AI response as JSON: {str(je)}. Raw output: {response.text[:200]}...")
    except Exception as e:
        raise RuntimeError(f"Gemini API Error: {str(e)}")
