# gemini_service.py
import os
import json
import re
import concurrent.futures
import google.generativeai as genai
import tenacity
from dotenv import load_dotenv
from prompts import SECTION_SYSTEM_INSTRUCTION, SECTION_TEMPLATES

# Load environment variables
load_dotenv()

# Retrieve API Key
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# Configure genai SDK if API key exists
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)

@tenacity.retry(
    stop=tenacity.stop_after_attempt(5),
    wait=tenacity.wait_random_exponential(min=2, max=15),
    reraise=True
)
def _generate_single_section(section_key: str, project_name: str, industry: str, features_str: str, scope_details: str, creativity_level: float) -> str:
    """
    Generates a single requirements section using the Gemini API.
    """
    template = SECTION_TEMPLATES.get(section_key)
    if not template:
        raise ValueError(f"No template found for section key: {section_key}")
        
    prompt = template.format(
        project_name=project_name,
        industry=industry,
        features=features_str,
        scope_details=scope_details,
        creativity_level=creativity_level
    )
    
    generation_config = genai.types.GenerationConfig(
        temperature=float(creativity_level),
        max_output_tokens=8192
    )
    
    try:
        model = genai.GenerativeModel(
            model_name="gemini-2.5-flash",
            system_instruction=SECTION_SYSTEM_INSTRUCTION
        )
        response = model.generate_content(prompt, generation_config=generation_config)
    except Exception as e:
        error_msg = str(e).lower()
        if "quota" in error_msg or "429" in error_msg or "limit" in error_msg or "exhausted" in error_msg:
            # Fallback to gemini-flash-lite-latest which has a high 1500 request/day limit
            try:
                fallback_model = genai.GenerativeModel(
                    model_name="gemini-flash-lite-latest",
                    system_instruction=SECTION_SYSTEM_INSTRUCTION
                )
                response = fallback_model.generate_content(prompt, generation_config=generation_config)
            except Exception as fallback_err:
                raise RuntimeError(f"Fallback to gemini-flash-latest failed: {fallback_err}. Original error: {e}")
        else:
            raise e
            
    if not response.text:
        return f"*Section {section_key} was empty or not generated by AI.*"
        
    cleaned_text = response.text.strip()
    
    # Strip markdown code blocks if the model accidentally wrapped its output in one
    if cleaned_text.startswith("```markdown"):
        cleaned_text = cleaned_text[11:]
    elif cleaned_text.startswith("```"):
        cleaned_text = cleaned_text[3:]
    if cleaned_text.endswith("```"):
        cleaned_text = cleaned_text[:-3]
        
    return cleaned_text.strip()


def generate_erp_requirements(project_name: str, industry: str, features: list, scope_details: str, creativity_level: float) -> dict:
    """
    Calls the Gemini API to generate all 8 ERP specification sections in parallel.
    
    Args:
        project_name (str): Name of the target ERP project.
        industry (str): Industry domain (e.g. FinTech, Healthcare).
        features (list): Selected core module names.
        scope_details (str): User-provided scope and context details.
        creativity_level (float): A value from 0.0 to 1.0 mapping to API temperature.
        
    Returns:
        dict: Parsed dictionary with keys: brd, srs, use_cases, user_stories, database_design, kpis, workflow, reports.
    """
    if not GEMINI_API_KEY:
        raise ValueError("GEMINI_API_KEY is not configured. Please define it in your .env file.")
        
    features_str = ", ".join(features) if features else "None selected"
    required_keys = ["brd", "srs", "use_cases", "user_stories", "database_design", "kpis", "workflow", "reports"]
    
    results = {}
    
    try:
        # Use ThreadPoolExecutor to run tasks in parallel
        with concurrent.futures.ThreadPoolExecutor(max_workers=len(required_keys)) as executor:
            # Submit all tasks
            future_to_key = {
                executor.submit(
                    _generate_single_section,
                    key,
                    project_name,
                    industry,
                    features_str,
                    scope_details,
                    creativity_level
                ): key for key in required_keys
            }
            
            # Collect results as they complete
            for future in concurrent.futures.as_completed(future_to_key):
                key = future_to_key[future]
                try:
                    content = future.result()
                    results[key] = content
                except Exception as e:
                    # Propagate errors cleanly
                    raise RuntimeError(f"Failed to generate section '{key}' with Gemini: {str(e)}")
                    
        # Ensure all required keys exist, fill with fallback if missing
        for key in required_keys:
            if key not in results:
                results[key] = f"*Section {key} was not generated due to a processing error.*"
                
        return results
        
    except Exception as e:
        raise RuntimeError(f"Gemini API Error: {str(e)}")

