"""
markdown_export.py — ReqFlow AI · Professional Markdown Export Engine
=====================================================================
Formats ERP requirement documents (BRD, SRS, Use Cases, User Stories,
Database Suggestions, KPIs, Workflow, Reports) to cleanly structured
Markdown files (.md) with enterprise title headers and timestamps.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional

# ---------------------------------------------------------------------------
# Public constants
# ---------------------------------------------------------------------------
MARKDOWN_MIME = "text/markdown"

_SECTION_META: dict[str, tuple[str, str]] = {
    "brd": ("Business Requirements Document", "BRD"),
    "srs": ("Software Requirements Specification", "SRS"),
    "use_cases": ("Use Case Specifications", "UC"),
    "user_stories": ("User Stories & Acceptance Criteria", "US"),
    "db_suggestions": ("Database Design Suggestions", "DB"),
    "kpis": ("Key Performance Indicators", "KPI"),
    "workflow": ("Workflow Specifications", "WF"),
    "reports": ("Report Specifications", "RPT"),
}

# ===========================================================================
#  Public API
# ===========================================================================
def build_markdown_document(
    project_name: str,
    industry: str,
    content: str,
    doc_label: str,
    timestamp: Optional[str] = None
) -> str:
    """
    Builds a single-section Markdown document with a standardized header banner.
    """
    ts = timestamp or datetime.now().strftime("%B %d, %Y at %H:%M")
    
    md = f"""# {doc_label.upper()}
    
=====================================================================
* **Project Name:** {project_name}
* **Industry Domain:** {industry}
* **Generated:** {ts}
* **System Tool:** ReqFlow AI Requirements Engine
=====================================================================

{content}
"""
    return md.strip() + "\n"


def build_complete_suite_markdown(
    project_name: str,
    industry: str,
    timestamp: Optional[str],
    sections: dict[str, str]
) -> str:
    """
    Builds a comprehensive multi-section Markdown document with a cover sheet,
    table of contents, and clean page dividers.
    """
    ts = timestamp or datetime.now().strftime("%B %d, %Y at %H:%M")
    
    # 1. Title/Cover banner
    md = f"""# REQFLOW AI — ENTERPRISE REQUIREMENTS SUITE
    
=====================================================================
* **Project Name:** {project_name}
* **Industry Domain:** {industry}
* **Generated:** {ts}
* **Status:** CONFIDENTIAL / internal Use Only
=====================================================================

## Table of Contents
"""
    
    # 2. Table of Contents
    idx = 1
    for key, val in _SECTION_META.items():
        content = sections.get(key, "")
        if content and content.strip() and not content.startswith("*"):
            title = val[0]
            anchor = title.lower().replace(" ", "-").replace("&", "").replace("(", "").replace(")", "")
            md += f"{idx}. [{title}](#{anchor})\n"
            idx += 1
            
    md += "\n---\n\n"
    
    # 3. Add active sections
    active_keys = [k for k, v in _SECTION_META.items() if sections.get(k) and not sections[k].startswith("*")]
    
    for i, key in enumerate(active_keys):
        title, code = _SECTION_META[key]
        content = sections[key]
        
        md += f"## {title}\n"
        md += f"*Code Ref: [{code}]*\n\n"
        md += f"{content.strip()}\n\n"
        
        if i < len(active_keys) - 1:
            md += "---\n\n"
            
    md += f"""---
*— End of Complete ERP Requirement Suite — {project_name} — Generated by ReqFlow AI on {ts} —*
"""
    return md
