"""
pdf_export.py — ReqFlow AI · Professional PDF Export Engine
============================================================
Converts ERP requirement documents (BRD, SRS, Use Cases, User Stories,
Database Suggestions, KPIs, Workflow, Reports) to beautifully formatted
PDF documents using ReportLab.
"""

from __future__ import annotations

import io
import re
from datetime import datetime
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable
)
from reportlab.pdfgen import canvas

# ---------------------------------------------------------------------------
# Public constants
# ---------------------------------------------------------------------------
PDF_MIME = "application/pdf"

# ReqFlow brand colours
_HEX_PURPLE = "#8B5CF6"
_HEX_INDIGO = "#6366F1"
_HEX_DARK = "#1E1B4B"
_HEX_BODY = "#1F2937"
_HEX_MUTED = "#4F46E5"
_HEX_TH_BG = "#EEE9FF"
_HEX_TH_TEXT = "#5B21B6"
_HEX_BORDER = "#E5E7EB"

# Section configurations
_SECTION_META: dict[str, tuple[str, str]] = {
    "brd": ("Business Requirements Document", "BRD"),
    "srs": ("Software Requirements Specification", "SRS"),
    "use_cases": ("Use Case Specifications", "UC"),
    "user_stories": ("User Stories & Acceptance Criteria", "US"),
    "db_suggestions": ("Database Design Suggestions", "DB"),
    "kpis": ("Key Performance Indicators", "KPI"),
    "workflow": ("Workflow Specifications", "WF"),
    "reports": ("Report Specifications", "RPT"),
}

# ===========================================================================
#  Numbered Canvas for Running Headers and Footers
# ===========================================================================
class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, total_pages: int):
        if self._pageNumber == 1:
            # Skip header/footer on cover page
            return

        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor(_HEX_BODY))
        
        # Draw header
        self.drawString(54, 750, "ReqFlow AI  |  Enterprise ERP Requirement Suite")
        self.setStrokeColor(colors.HexColor(_HEX_BORDER))
        self.setLineWidth(0.5)
        self.line(54, 742, 558, 742)

        # Draw footer
        self.drawString(54, 45, "CONFIDENTIAL — Generated by ReqFlow AI")
        page_str = f"Page {self._pageNumber} of {total_pages}"
        self.drawRightString(558, 45, page_str)
        self.restoreState()


# ===========================================================================
#  Markdown → ReportLab Flowables Parser
# ===========================================================================
def _parse_inline_markdown(text: str) -> str:
    """Safely converts simple markdown (bold, code) into HTML tags for Paragraph."""
    # Escape existing HTML brackets to prevent parsing issues
    text = text.replace("<", "&lt;").replace(">", "&gt;")
    # Bold **text**
    text = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", text)
    # Code `text`
    text = re.sub(r"`([^`]+)`", r"<font face='Courier' color='#4F46E5'>\1</font>", text)
    return text


def _flush_pdf_table(story: list, table_lines: list, body_style: ParagraphStyle, header_style: ParagraphStyle) -> None:
    parsed_rows = []
    for line in table_lines:
        # Skip divider rows (e.g. |---|---|)
        if re.match(r"^\|[\s\-:|]+\|$", line.strip()):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        parsed_rows.append(cells)
        
    if not parsed_rows:
        return
        
    cols_count = max(len(r) for r in parsed_rows)
    table_data = []
    
    for r_idx, row in enumerate(parsed_rows):
        formatted_row = []
        for c_idx in range(cols_count):
            cell_text = row[c_idx] if c_idx < len(row) else ""
            html_text = _parse_inline_markdown(cell_text)
            if r_idx == 0:
                p = Paragraph(f"<b>{html_text}</b>", header_style)
            else:
                p = Paragraph(html_text, body_style)
            formatted_row.append(p)
        table_data.append(formatted_row)

    # Let each column take an equal slice of the page printable area (approx 500pt width)
    col_width = 504.0 / cols_count
    t = Table(table_data, colWidths=[col_width] * cols_count)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor(_HEX_TH_BG)),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor(_HEX_BORDER)),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor(_HEX_BORDER)),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    
    story.append(t)
    story.append(Spacer(1, 10))


def _append_markdown_to_story(story: list, markdown: str, styles: dict) -> None:
    lines = (markdown or "").splitlines()
    in_code = False
    table_buf = []

    for raw in lines:
        line = raw.rstrip()

        # Handle Code Fences
        if re.match(r"^```", line):
            if in_code:
                in_code = False
                story.append(Spacer(1, 6))
            else:
                if table_buf:
                    _flush_pdf_table(story, table_buf, styles["CustomBodyText"], styles["TableHeader"])
                    table_buf.clear()
                in_code = True
            continue

        if in_code:
            # Code line
            story.append(Paragraph(f"<font face='Courier'>{line}</font>", styles["CodeBlock"]))
            continue

        # Handle Tables
        if re.match(r"^\|(.+)\|$", line):
            table_buf.append(line)
            continue
        else:
            if table_buf:
                _flush_pdf_table(story, table_buf, styles["CustomBodyText"], styles["TableHeader"])
                table_buf.clear()

        # Horizontal rules
        if re.match(r"^[-_*]{3,}$", line.strip()):
            story.append(Spacer(1, 4))
            story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor(_HEX_PURPLE), spaceAfter=8))
            continue

        # Headings
        m = re.match(r"^#\s+(.+)$", line)
        if m:
            story.append(Paragraph(m.group(1), styles["CustomH1"]))
            continue

        m = re.match(r"^##\s+(.+)$", line)
        if m:
            story.append(Paragraph(m.group(1), styles["CustomH2"]))
            continue

        m = re.match(r"^###\s+(.+)$", line)
        if m:
            story.append(Paragraph(m.group(1), styles["CustomH3"]))
            continue

        m = re.match(r"^####\s+(.+)$", line)
        if m:
            story.append(Paragraph(m.group(1), styles["CustomH4"]))
            continue

        # Lists (Bullets and Numbers)
        m = re.match(r"^[-*\u2022]\s+(.+)$", line)
        if m:
            html = _parse_inline_markdown(m.group(1))
            story.append(Paragraph(f"&bull; &nbsp; {html}", styles["CustomBullet"]))
            continue

        m = re.match(r"^(\d+)\.\s+(.+)$", line)
        if m:
            num = m.group(1)
            html = _parse_inline_markdown(m.group(2))
            story.append(Paragraph(f"{num}. &nbsp; {html}", styles["CustomNumber"]))
            continue

        # Blank lines
        if not line.strip():
            story.append(Spacer(1, 6))
            continue

        # Paragraphs
        html = _parse_inline_markdown(line)
        story.append(Paragraph(html, styles["CustomBodyText"]))

    # Flush remaining table
    if table_buf:
        _flush_pdf_table(story, table_buf, styles["CustomBodyText"], styles["TableHeader"])


# ===========================================================================
#  Style Configuration Loader
# ===========================================================================
def _get_pdf_styles() -> dict:
    styles = getSampleStyleSheet()
    
    # Custom heading and list styles
    styles.add(ParagraphStyle(
        name="CustomH1",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        textColor=colors.HexColor(_HEX_DARK),
        spaceBefore=14,
        spaceAfter=10,
        keepWithNext=True
    ))
    
    styles.add(ParagraphStyle(
        name="CustomH2",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        textColor=colors.HexColor(_HEX_PURPLE),
        spaceBefore=12,
        spaceAfter=8,
        keepWithNext=True
    ))

    styles.add(ParagraphStyle(
        name="CustomH3",
        parent=styles["Heading3"],
        fontName="Helvetica-Bold",
        fontSize=11.5,
        leading=15,
        textColor=colors.HexColor(_HEX_MUTED),
        spaceBefore=10,
        spaceAfter=6,
        keepWithNext=True
    ))

    styles.add(ParagraphStyle(
        name="CustomH4",
        parent=styles["Heading4"],
        fontName="Helvetica-Bold",
        fontSize=10,
        leading=13,
        textColor=colors.HexColor(_HEX_BODY),
        spaceBefore=8,
        spaceAfter=4,
        keepWithNext=True
    ))

    styles.add(ParagraphStyle(
        name="CustomBodyText",
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor(_HEX_BODY),
        spaceAfter=6
    ))

    styles.add(ParagraphStyle(
        name="TableHeader",
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=11,
        textColor=colors.HexColor(_HEX_TH_TEXT)
    ))

    styles.add(ParagraphStyle(
        name="CodeBlock",
        fontName="Courier",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor(_HEX_MUTED),
        leftIndent=15,
        spaceAfter=2
    ))

    styles.add(ParagraphStyle(
        name="CustomBullet",
        parent=styles["CustomBodyText"],
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=3
    ))

    styles.add(ParagraphStyle(
        name="CustomNumber",
        parent=styles["CustomBodyText"],
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=3
    ))

    # Cover Page specific styles
    styles.add(ParagraphStyle(
        name="CoverBrand",
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        textColor=colors.HexColor(_HEX_PURPLE),
        alignment=1, # Center
        spaceAfter=15
    ))

    styles.add(ParagraphStyle(
        name="CoverSub",
        fontName="Helvetica",
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#6B7280"),
        alignment=1, # Center
        spaceAfter=25
    ))

    styles.add(ParagraphStyle(
        name="CoverTitle",
        fontName="Helvetica-Bold",
        fontSize=28,
        leading=34,
        textColor=colors.HexColor(_HEX_DARK),
        alignment=1, # Center
        spaceAfter=25
    ))

    styles.add(ParagraphStyle(
        name="CoverMeta",
        fontName="Helvetica",
        fontSize=10.5,
        leading=15,
        textColor=colors.HexColor(_HEX_MUTED),
        alignment=1, # Center
        spaceAfter=10
    ))

    styles.add(ParagraphStyle(
        name="CoverTime",
        fontName="Helvetica",
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#6B7280"),
        alignment=1, # Center
        spaceAfter=40
    ))

    styles.add(ParagraphStyle(
        name="CoverFoot",
        fontName="Helvetica-Oblique",
        fontSize=8.5,
        leading=12,
        textColor=colors.HexColor("#6B7280"),
        alignment=1, # Center
    ))

    styles.add(ParagraphStyle(
        name="TOCItem",
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor(_HEX_MUTED),
        leftIndent=20,
        spaceAfter=4
    ))

    return styles


# ===========================================================================
#  Cover & Meta Layout Builders
# ===========================================================================
def _add_cover_flowables(story: list, styles: dict, project_name: str, industry: str, doc_type: str, timestamp: str) -> None:
    story.append(Spacer(1, 1.2 * inch))
    story.append(Paragraph("ReqFlow AI  |  ERP Requirement Engine", styles["CoverBrand"]))
    story.append(Paragraph(doc_type.upper(), styles["CoverSub"]))
    
    # Large Title
    story.append(HRFlowable(width="60%", thickness=1.5, color=colors.HexColor(_HEX_PURPLE), spaceAfter=15))
    story.append(Paragraph(project_name, styles["CoverTitle"]))
    story.append(HRFlowable(width="60%", thickness=1.5, color=colors.HexColor(_HEX_PURPLE), spaceAfter=20))
    
    # Metadata details
    story.append(Paragraph(f"Industry Domain: {industry}", styles["CoverMeta"]))
    story.append(Paragraph(f"Generated: {timestamp}", styles["CoverTime"]))
    
    story.append(Spacer(1, 1 * inch))
    story.append(Paragraph(
        "CONFIDENTIAL — For internal use only.<br/>"
        "Generated automatically by ReqFlow AI Enterprise.",
        styles["CoverFoot"]
    ))
    story.append(PageBreak())


def _add_meta_table_flowable(story: list, styles: dict, project_name: str, industry: str, doc_label: str, timestamp: str) -> None:
    data = [
        [Paragraph("<b>Project</b>", styles["TableHeader"]), Paragraph(project_name, styles["CustomBodyText"])],
        [Paragraph("<b>Industry</b>", styles["TableHeader"]), Paragraph(industry, styles["CustomBodyText"])],
        [Paragraph("<b>Document</b>", styles["TableHeader"]), Paragraph(doc_label, styles["CustomBodyText"])],
        [Paragraph("<b>Generated</b>", styles["TableHeader"]), Paragraph(timestamp, styles["CustomBodyText"])],
        [Paragraph("<b>Tool</b>", styles["TableHeader"]), Paragraph("ReqFlow AI — ERP Requirement Engine", styles["CustomBodyText"])],
    ]
    t = Table(data, colWidths=[1.8 * inch, 5.2 * inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor(_HEX_TH_BG)),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor(_HEX_BORDER)),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor(_HEX_BORDER)),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
    ]))
    story.append(t)
    story.append(Spacer(1, 15))


# ===========================================================================
#  Public API
# ===========================================================================
def build_pdf_document(
    project_name: str,
    industry: str,
    content: str,
    doc_label: str,
    timestamp: Optional[str] = None
) -> bytes:
    """
    Builds a single-section PDF document.
    """
    ts = timestamp or datetime.now().strftime("%B %d, %Y at %H:%M")
    styles = _get_pdf_styles()
    
    pdf_buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        pdf_buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54
    )
    
    story = []
    _add_cover_flowables(story, styles, project_name, industry, doc_label, ts)
    _add_meta_table_flowable(story, styles, project_name, industry, doc_label, ts)
    
    # Parse Markdown content
    _append_markdown_to_story(story, content, styles)
    
    # End note
    story.append(Spacer(1, 15))
    story.append(Paragraph(
        f"<i>— End of {doc_label} — {project_name} — Generated by ReqFlow AI — {ts}</i>",
        styles["CoverFoot"]
    ))
    
    doc.build(story, canvasmaker=NumberedCanvas)
    pdf_buffer.seek(0)
    return pdf_buffer.read()


def build_complete_suite_pdf(
    project_name: str,
    industry: str,
    timestamp: Optional[str],
    sections: dict[str, str]
) -> bytes:
    """
    Builds a comprehensive ERP Requirement Suite PDF containing all available sections.
    """
    ts = timestamp or datetime.now().strftime("%B %d, %Y at %H:%M")
    styles = _get_pdf_styles()
    
    pdf_buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        pdf_buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54
    )
    
    story = []
    _add_cover_flowables(story, styles, project_name, industry, "Complete ERP Requirement Suite", ts)
    
    # Render Table of Contents Page
    story.append(Paragraph("Table of Contents", styles["CustomH1"]))
    story.append(Spacer(1, 10))
    
    idx = 1
    for key, val in _SECTION_META.items():
        content = sections.get(key, "")
        if content and content.strip() and not content.startswith("*"):
            title = val[0]
            story.append(Paragraph(f"{idx}. &nbsp; {title}", styles["TOCItem"]))
            idx += 1
            
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor(_HEX_PURPLE), spaceAfter=15))
    _add_meta_table_flowable(story, styles, project_name, industry, "Complete ERP Requirement Suite", ts)
    story.append(PageBreak())
    
    # Render sections
    active_keys = [k for k, v in _SECTION_META.items() if sections.get(k) and not sections[k].startswith("*")]
    
    for i, key in enumerate(active_keys):
        title, code = _SECTION_META[key]
        content = sections[key]
        
        # Section Header
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor(_HEX_PURPLE), spaceAfter=10))
        story.append(Paragraph(f"[{code}] &nbsp; {title}", styles["CustomH1"]))
        story.append(Spacer(1, 10))
        
        _append_markdown_to_story(story, content, styles)
        
        # Page break if not final section
        if i < len(active_keys) - 1:
            story.append(PageBreak())
            
    # Final footer flowable
    story.append(Spacer(1, 20))
    story.append(Paragraph(
        f"<i>— End of Complete ERP Requirement Suite — {project_name} — Generated by ReqFlow AI — {ts}</i>",
        styles["CoverFoot"]
    ))
    
    doc.build(story, canvasmaker=NumberedCanvas)
    pdf_buffer.seek(0)
    return pdf_buffer.read()
