# prompts.py

BRD_SYSTEM_INSTRUCTION = (
    "You are a Principal Enterprise Systems Architect and Senior Business Analyst with 20+ years of experience "
    "designing large-scale ERP and SaaS solutions across all industry domains.\n\n"
    "Your task is to generate a comprehensive, professional, and well-structured ERP Requirements Suite. "
    "Return output STRICTLY as a single valid JSON object. No text outside the JSON. "
    "Each JSON value must be a Markdown string exactly following the provided international templates. "
    "Use bullet points, bold text, markdown tables, and clear headings as requested. "
    "Never use placeholders. Use realistic names, IDs, metrics, and domain-specific terminology. "
    "Escape all newlines inside JSON string values as \\n and all internal double-quotes as \\\"."
)

BRD_PROMPT_TEMPLATE = (
    "Generate a complete professional ERP Requirements Suite.\n\n"
    "Project Configuration:\n"
    "- Project Name: {project_name}\n"
    "- Industry Domain: {industry}\n"
    "- Target Core Modules: {features}\n"
    "- Scope and Context: {scope_details}\n"
    "- Detail Level (0.0 = concise, 1.0 = comprehensive): {creativity_level}\n\n"
    "Return a single JSON object with EXACTLY these 8 keys. Each value is a Markdown string.\n"
    "CRITICAL INSTRUCTION: You MUST use the EXACT Markdown structure provided below. Do NOT remove any markdown headings (##), bold labels (**Label:**), or tables. ONLY replace the instructional text inside the curly braces {{...}} with your highly detailed, domain-specific content. KEEP the bold labels intact!\n\n"

    "KEY 1 - brd (Business Requirements Document):\n"
    "# Business Requirements Document (BRD) - {project_name} ERP\n"
    "## 1. Executive Summary\n"
    "* **Project Overview:** {{Write a highly detailed paragraph describing the project initiative, its purpose, and business value.}}\n"
    "* **Business Objectives:**\n"
    "  - {{List measurable goal 1}}\n"
    "  - {{List measurable goal 2}}\n"
    "  - {{List measurable goal 3}}\n"
    "* **Project Scope:** {{List the exact modules that are in-scope ({features}) and give examples of what is out-of-scope for phase 1.}}\n\n"
    "## 2. Business Drivers & Goals\n"
    "* **Current State / Problem Statement:** {{Describe realistic legacy silos, manual inefficiencies, or specific problems in {industry} that justify this ERP.}}\n"
    "* **Future State Vision:** {{Describe the expected operational improvements once the system is live.}}\n"
    "* **Financial Goals:** {{Describe realistic expected ROI, cost reductions, or efficiency gains for this industry.}}\n\n"
    "## 3. Stakeholder Analysis\n"
    "* **Sponsors:** {{Identify realistic executive roles funding the project, e.g., CFO, COO.}}\n"
    "* **Key Stakeholders:** {{Identify specific department heads involved, e.g., VP of Supply Chain, Head of HR.}}\n"
    "* **End Users:** {{Identify daily operational staff roles who will use the system.}}\n\n"
    "## 4. High-Level Business Requirements (Functional Grouping)\n"
    "| Req ID | Business Process | Requirement Description | Priority (P1/P2/P3) |\n"
    "|---|---|---|---|\n"
    "| BRD-001 | {{Process Name}} | {{Detailed technical requirement description}} | P1 |\n"
    "| BRD-002 | {{Process Name}} | {{Detailed technical requirement description}} | P1 |\n"
    "| BRD-003 | {{Process Name}} | {{Detailed technical requirement description}} | P2 |\n"
    "| BRD-004 | {{Process Name}} | {{Detailed technical requirement description}} | P2 |\n"
    "| BRD-005 | {{Process Name}} | {{Detailed technical requirement description}} | P3 |\n\n"
    "## 5. Non-Functional Business Constraints\n"
    "* **Regulatory Compliance:** {{List exact compliance standards relevant to {industry}, e.g., HIPAA, GDPR, SOX, PCI-DSS, ISO.}}\n"
    "* **Localization:** {{Describe specific language, currency, or regional tax code support needed.}}\n"
    "* **Budget & Timeline:** {{Provide a realistic hypothetical timeline constraint, e.g., 9-month phased rollout.}}\n\n"

    "KEY 2 - srs (Software Requirements Specification):\n"
    "# Software Requirements Specification (SRS) - {project_name} ERP\n"
    "## 1. Introduction\n"
    "* **Purpose:** {{Specify the technical purpose and behavioral requirements of the ERP.}}\n"
    "* **System Overview:** {{Describe the high-level architectural approach, e.g., Microservices, Event-driven.}}\n\n"
    "## 2. Overall Description\n"
    "* **System Interfaces:** {{List specific third-party APIs or legacy systems it must integrate with.}}\n"
    "* **User Characteristics:** {{Describe the technical proficiency of users and access patterns.}}\n"
    "* **Assumptions & Dependencies:** {{List technical assumptions, e.g., cloud hosting, API limits.}}\n\n"
    "## 3. System Features & Functional Requirements\n"
    "### 3.1 {{Module Name 1}}\n"
    "* **Description:** {{Detailed description of the module.}}\n"
    "* **Functional Specs:**\n"
    "  * **SRS-MOD1-001:** {{Highly specific functional requirement.}}\n"
    "  * **SRS-MOD1-002:** {{Highly specific functional requirement.}}\n"
    "  * **SRS-MOD1-003:** {{Highly specific functional requirement.}}\n\n"
    "### 3.2 {{Module Name 2}}\n"
    "* **Description:** {{Detailed description of the module.}}\n"
    "* **Functional Specs:**\n"
    "  * **SRS-MOD2-001:** {{Highly specific functional requirement.}}\n"
    "  * **SRS-MOD2-002:** {{Highly specific functional requirement.}}\n"
    "  * **SRS-MOD2-003:** {{Highly specific functional requirement.}}\n\n"
    "## 4. Non-Functional Requirements (NFRs)\n"
    "* **Performance:** {{Specify exact page load times, API response targets, e.g., under 500ms.}}\n"
    "* **Scalability:** {{Specify support for concurrent active users based on enterprise scale.}}\n"
    "* **Availability:** {{Specify uptime targets, e.g., 99.99% High Availability.}}\n"
    "* **Security:** {{Specify encryption standards, e.g., AES-256, TLS 1.3, MFA.}}\n\n"
    "## 5. Data & Compliance Architecture\n"
    "* {{Describe specific data retention policies and disaster recovery rules.}}\n\n"

    "KEY 3 - use_cases (Use Case Specifications):\n"
    "# Use Case Template: UC-001 {{Realistic Use Case Name 1}}\n"
    "* **Actor(s):** {{Specific User Role}}\n"
    "* **Pre-conditions:** {{Specific state before action}}\n"
    "* **Post-conditions:** {{Specific state after action}}\n\n"
    "### Main Success Scenario (Happy Path)\n"
    "1. {{Actor does step 1}}\n"
    "2. {{System responds step 2}}\n"
    "3. {{Actor does step 3}}\n"
    "4. {{System responds step 4}}\n"
    "5. {{Process completes}}\n\n"
    "### Alternative / Exception Flows\n"
    "* **Alt Flow 2a (Title):** {{System prompts the actor to...}}\n"
    "* **Exception Flow 4a (Title):** {{If validation fails, system routes...}}\n\n"
    "# Use Case Template: UC-002 {{Realistic Use Case Name 2}}\n"
    "* **Actor(s):** {{Specific User Role}}\n"
    "* **Pre-conditions:** {{Specific state before action}}\n"
    "* **Post-conditions:** {{Specific state after action}}\n\n"
    "### Main Success Scenario (Happy Path)\n"
    "1. {{Actor does step 1}}\n"
    "2. {{System responds step 2}}\n"
    "3. {{Actor does step 3}}\n"
    "4. {{System responds step 4}}\n"
    "5. {{Process completes}}\n\n"
    "### Alternative / Exception Flows\n"
    "* **Alt Flow 2a (Title):** {{System prompts the actor to...}}\n"
    "* **Exception Flow 4a (Title):** {{If validation fails, system routes...}}\n\n"

    "KEY 4 - user_stories (User Stories and Acceptance Criteria):\n"
    "# User Story Epic: {{Provide a realistic Epic Name}}\n\n"
    "## US-101: {{Story Title}}\n"
    "**As a** {{Role}},\n"
    "**I want** {{Action}},\n"
    "**So that** {{Business Value}}.\n\n"
    "* **Acceptance Criteria:**\n"
    " - Given {{context}}, when {{action}}, then {{result}}.\n"
    " - Given {{context}}, when {{action}}, then {{result}}.\n"
    " - Given {{context}}, when {{action}}, then {{result}}.\n\n"
    "## US-102: {{Story Title}}\n"
    "**As a** {{Role}},\n"
    "**I want** {{Action}},\n"
    "**So that** {{Business Value}}.\n\n"
    "* **Acceptance Criteria:**\n"
    " - Given {{context}}, when {{action}}, then {{result}}.\n"
    " - Given {{context}}, when {{action}}, then {{result}}.\n"
    " - Given {{context}}, when {{action}}, then {{result}}.\n\n"

    "KEY 5 - database_design (Database Design Suggestions):\n"
    "## Core ERP Database Design Strategy\n"
    "* **Database Engine:** {{Suggest an engine e.g. PostgreSQL and explain why for this project.}}\n"
    "* **Audit Trail:** {{Explain audit strategy, soft deletes vs hard deletes.}}\n\n"
    "## Sample Physical/Logical Schema Structure\n"
    "{{table_name_1}}\n"
    " - id (UUID, PK)\n"
    " - {{column_name}} (VARCHAR)\n"
    " - {{column_name}} (NUMERIC)\n"
    " - {{column_name}} (TIMESTAMP)\n"
    " - {{column_name}} (UUID, FK)\n\n"
    "{{table_name_2}}\n"
    " - id (UUID, PK)\n"
    " - {{column_name}} (VARCHAR)\n"
    " - {{column_name}} (NUMERIC)\n"
    " - {{column_name}} (TIMESTAMP)\n"
    " - {{column_name}} (UUID, FK)\n\n"

    "KEY 6 - kpis (Key Performance Indicators):\n"
    "# Key Performance Indicators (KPIs)\n"
    "Your ERP should measure both operational metrics (business success) and technical metrics (system performance).\n\n"
    "## Business Operations KPIs\n"
    "* **Financials:** {{List 2-3 detailed financial KPIs like DSO, DPO, etc.}}\n"
    "* **Operations:** {{List 2-3 detailed operational KPIs relevant to the selected modules.}}\n"
    "* **HR / Core:** {{List 2-3 detailed internal KPIs.}}\n\n"
    "## Technical & System KPIs\n"
    "* **User Adoption Rate:** {{Define the metric.}}\n"
    "* **Data Accuracy Rate:** {{Define the metric.}}\n"
    "* **System Uptime & Latency:** {{Define the metric.}}\n\n"

    "KEY 7 - workflow (Workflow Specifications):\n"
    "# Workflows (BPMN 2.0 Framework)\n"
    "Workflows define how data moves across departments.\n\n"
    "## {{Generate a Realistic Process Name}} Cross-Functional Workflow\n"
    "1. **{{Actor/Dept 1}}:** {{Detailed Action}} -> {{Resulting System State}}\n"
    "2. **{{Actor/Dept 2}}:** {{Detailed Action}} -> {{Resulting System State}}\n"
    "3. **{{Actor/Dept 3}}:** {{Detailed Action}} -> {{Resulting System State}}\n"
    "4. **{{Actor/Dept 4}}:** {{Detailed Action}} -> {{Resulting System State}}\n"
    "5. **{{Actor/Dept 5}}:** {{Detailed Action}} -> {{Resulting System State}}\n\n"

    "KEY 8 - reports (Report Specifications):\n"
    "# Reports Framework\n"
    "ERP reports must serve multiple organizational tiers: Operational, Tactical, and Strategic.\n\n"
    "| Report Name | Module | Target Audience | Key Data Fields Included | Frequency |\n"
    "|---|---|---|---|---|\n"
    "| {{Report Name}} | {{Module}} | {{Target Audience}} | {{Key Data Fields Included}} | {{Frequency}} |\n"
    "| {{Report Name}} | {{Module}} | {{Target Audience}} | {{Key Data Fields Included}} | {{Frequency}} |\n"
    "| {{Report Name}} | {{Module}} | {{Target Audience}} | {{Key Data Fields Included}} | {{Frequency}} |\n"
    "| {{Report Name}} | {{Module}} | {{Target Audience}} | {{Key Data Fields Included}} | {{Frequency}} |\n"
    "| {{Report Name}} | {{Module}} | {{Target Audience}} | {{Key Data Fields Included}} | {{Frequency}} |\n\n"

    "Final Rules:\n"
    "- ONLY replace the text inside {{...}}. Do NOT remove the bold formatting like `* **Project Overview:**`.\n"
    "- Ensure your replacements are deeply detailed, highly technical, and strictly relevant to {project_name} and {industry}.\n"
    "- Return valid JSON only - escape newlines as \\n and internal quotes as \\\"\n"
)

SECTION_SYSTEM_INSTRUCTION = (
    "You are a Principal Enterprise Systems Architect and Senior Business Analyst with 20+ years of experience "
    "designing large-scale ERP and SaaS solutions across all industry domains.\n\n"
    "Your task is to generate a comprehensive, professional, and well-structured ERP Requirements document section. "
    "Return output STRICTLY as raw Markdown. Do NOT wrap the output in JSON. Do NOT wrap the entire response in a markdown code block (like ```markdown ... ```). "
    "Use bullet points, bold text, markdown tables, and clear headings as requested. "
    "Never use placeholders. Use realistic names, IDs, metrics, and domain-specific terminology."
)

SECTION_TEMPLATES = {
    "brd": (
        "Generate the Business Requirements Document (BRD) section.\n\n"
        "Project Configuration:\n"
        "- Project Name: {project_name}\n"
        "- Industry Domain: {industry}\n"
        "- Target Core Modules: {features}\n"
        "- Scope and Context: {scope_details}\n"
        "- Detail Level (0.0 = concise, 1.0 = comprehensive): {creativity_level}\n\n"
        "CRITICAL INSTRUCTION: You MUST use the EXACT Markdown structure provided below. Do NOT remove any markdown headings (##), bold labels (**Label:**), or tables. ONLY replace the instructional text inside the curly braces {{...}} with your highly detailed, domain-specific content. KEEP the bold labels intact!\n\n"
        "# Business Requirements Document (BRD) - {project_name} ERP\n"
        "## 1. Executive Summary\n"
        "* **Project Overview:** {{Write a highly detailed paragraph describing the project initiative, its purpose, and business value.}}\n"
        "* **Business Objectives:**\n"
        "  - {{List measurable goal 1}}\n"
        "  - {{List measurable goal 2}}\n"
        "  - {{List measurable goal 3}}\n"
        "* **Project Scope:** {{List the exact modules that are in-scope ({features}) and give examples of what is out-of-scope for phase 1.}}\n\n"
        "## 2. Business Drivers & Goals\n"
        "* **Current State / Problem Statement:** {{Describe realistic legacy silos, manual inefficiencies, or specific problems in {industry} that justify this ERP.}}\n"
        "* **Future State Vision:** {{Describe the expected operational improvements once the system is live.}}\n"
        "* **Financial Goals:** {{Describe realistic expected ROI, cost reductions, or efficiency gains for this industry.}}\n\n"
        "## 3. Stakeholder Analysis\n"
        "* **Sponsors:** {{Identify realistic executive roles funding the project, e.g., CFO, COO.}}\n"
        "* **Key Stakeholders:** {{Identify specific department heads involved, e.g., VP of Supply Chain, Head of HR.}}\n"
        "* **End Users:** {{Identify daily operational staff roles who will use the system.}}\n\n"
        "## 4. High-Level Business Requirements (Functional Grouping)\n"
        "| Req ID | Business Process | Requirement Description | Priority (P1/P2/P3) |\n"
        "|---|---|---|---|\n"
        "| BRD-001 | {{Process Name}} | {{Detailed technical requirement description}} | P1 |\n"
        "| BRD-002 | {{Process Name}} | {{Detailed technical requirement description}} | P1 |\n"
        "| BRD-003 | {{Process Name}} | {{Detailed technical requirement description}} | P2 |\n"
        "| BRD-004 | {{Process Name}} | {{Detailed technical requirement description}} | P2 |\n"
        "| BRD-005 | {{Process Name}} | {{Detailed technical requirement description}} | P3 |\n\n"
        "## 5. Non-Functional Business Constraints\n"
        "* **Regulatory Compliance:** {{List exact compliance standards relevant to {industry}, e.g., HIPAA, GDPR, SOX, PCI-DSS, ISO.}}\n"
        "* **Localization:** {{Describe specific language, currency, or regional tax code support needed.}}\n"
        "* **Budget & Timeline:** {{Provide a realistic hypothetical timeline constraint, e.g., 9-month phased rollout.}}\n\n"
        "Final Rules:\n"
        "- ONLY replace the text inside {{...}}. Do NOT remove the bold formatting like `* **Project Overview:**`.\n"
        "- Ensure your replacements are deeply detailed, highly technical, and strictly relevant to {project_name} and {industry}."
    ),
    "srs": (
        "Generate the Software Requirements Specification (SRS) section.\n\n"
        "Project Configuration:\n"
        "- Project Name: {project_name}\n"
        "- Industry Domain: {industry}\n"
        "- Target Core Modules: {features}\n"
        "- Scope and Context: {scope_details}\n"
        "- Detail Level (0.0 = concise, 1.0 = comprehensive): {creativity_level}\n\n"
        "CRITICAL INSTRUCTION: You MUST use the EXACT Markdown structure provided below. Do NOT remove any markdown headings (##), bold labels (**Label:**), or tables. ONLY replace the instructional text inside the curly braces {{...}} with your highly detailed, domain-specific content. KEEP the bold labels intact!\n\n"
        "# Software Requirements Specification (SRS) - {project_name} ERP\n"
        "## 1. Introduction\n"
        "* **Purpose:** {{Specify the technical purpose and behavioral requirements of the ERP.}}\n"
        "* **System Overview:** {{Describe the high-level architectural approach, e.g., Microservices, Event-driven.}}\n\n"
        "## 2. Overall Description\n"
        "* **System Interfaces:** {{List specific third-party APIs or legacy systems it must integrate with.}}\n"
        "* **User Characteristics:** {{Describe the technical proficiency of users and access patterns.}}\n"
        "* **Assumptions & Dependencies:** {{List technical assumptions, e.g., cloud hosting, API limits.}}\n\n"
        "## 3. System Features & Functional Requirements\n"
        "### 3.1 {{Module Name 1}}\n"
        "* **Description:** {{Detailed description of the module.}}\n"
        "* **Functional Specs:**\n"
        "  * **SRS-MOD1-001:** {{Highly specific functional requirement.}}\n"
        "  * **SRS-MOD1-002:** {{Highly specific functional requirement.}}\n"
        "  * **SRS-MOD1-003:** {{Highly specific functional requirement.}}\n\n"
        "### 3.2 {{Module Name 2}}\n"
        "* **Description:** {{Detailed description of the module.}}\n"
        "* **Functional Specs:**\n"
        "  * **SRS-MOD2-001:** {{Highly specific functional requirement.}}\n"
        "  * **SRS-MOD2-002:** {{Highly specific functional requirement.}}\n"
        "  * **SRS-MOD2-003:** {{Highly specific functional requirement.}}\n\n"
        "## 4. Non-Functional Requirements (NFRs)\n"
        "* **Performance:** {{Specify exact page load times, API response targets, e.g., under 500ms.}}\n"
        "* **Scalability:** {{Specify support for concurrent active users based on enterprise scale.}}\n"
        "* **Availability:** {{Specify uptime targets, e.g., 99.99% High Availability.}}\n"
        "* **Security:** {{Specify encryption standards, e.g., AES-256, TLS 1.3, MFA.}}\n\n"
        "## 5. Data & Compliance Architecture\n"
        "* {{Describe specific data retention policies and disaster recovery rules.}}\n\n"
        "Final Rules:\n"
        "- ONLY replace the text inside {{...}}. Do NOT remove the bold formatting.\n"
        "- Ensure your replacements are deeply detailed, highly technical, and strictly relevant to {project_name} and {industry}."
    ),
    "use_cases": (
        "Generate the Use Case Specifications section.\n\n"
        "Project Configuration:\n"
        "- Project Name: {project_name}\n"
        "- Industry Domain: {industry}\n"
        "- Target Core Modules: {features}\n"
        "- Scope and Context: {scope_details}\n"
        "- Detail Level (0.0 = concise, 1.0 = comprehensive): {creativity_level}\n\n"
        "CRITICAL INSTRUCTION: You MUST use the EXACT Markdown structure provided below. Do NOT remove any markdown headings (##), bold labels (**Label:**), or tables. ONLY replace the instructional text inside the curly braces {{...}} with your highly detailed, domain-specific content. KEEP the bold labels intact!\n\n"
        "# Use Case Template: UC-001 {{Realistic Use Case Name 1}}\n"
        "* **Actor(s):** {{Specific User Role}}\n"
        "* **Pre-conditions:** {{Specific state before action}}\n"
        "* **Post-conditions:** {{Specific state after action}}\n\n"
        "### Main Success Scenario (Happy Path)\n"
        "1. {{Actor does step 1}}\n"
        "2. {{System responds step 2}}\n"
        "3. {{Actor does step 3}}\n"
        "4. {{System responds step 4}}\n"
        "5. {{Process completes}}\n\n"
        "### Alternative / Exception Flows\n"
        "* **Alt Flow 2a (Title):** {{System prompts the actor to...}}\n"
        "* **Exception Flow 4a (Title):** {{If validation fails, system routes...}}\n\n"
        "# Use Case Template: UC-002 {{Realistic Use Case Name 2}}\n"
        "* **Actor(s):** {{Specific User Role}}\n"
        "* **Pre-conditions:** {{Specific state before action}}\n"
        "* **Post-conditions:** {{Specific state after action}}\n\n"
        "### Main Success Scenario (Happy Path)\n"
        "1. {{Actor does step 1}}\n"
        "2. {{System responds step 2}}\n"
        "3. {{Actor does step 3}}\n"
        "4. {{System responds step 4}}\n"
        "5. {{Process completes}}\n\n"
        "### Alternative / Exception Flows\n"
        "* **Alt Flow 2a (Title):** {{System prompts the actor to...}}\n"
        "* **Exception Flow 4a (Title):** {{If validation fails, system routes...}}\n\n"
        "Final Rules:\n"
        "- ONLY replace the text inside {{...}}. Do NOT remove the bold formatting.\n"
        "- Ensure your replacements are deeply detailed, highly technical, and strictly relevant to {project_name} and {industry}."
    ),
    "user_stories": (
        "Generate the User Stories and Acceptance Criteria section.\n\n"
        "Project Configuration:\n"
        "- Project Name: {project_name}\n"
        "- Industry Domain: {industry}\n"
        "- Target Core Modules: {features}\n"
        "- Scope and Context: {scope_details}\n"
        "- Detail Level (0.0 = concise, 1.0 = comprehensive): {creativity_level}\n\n"
        "CRITICAL INSTRUCTION: You MUST use the EXACT Markdown structure provided below. Do NOT remove any markdown headings (##), bold labels (**Label:**), or tables. ONLY replace the instructional text inside the curly braces {{...}} with your highly detailed, domain-specific content. KEEP the bold labels intact!\n\n"
        "# User Story Epic: {{Provide a realistic Epic Name}}\n\n"
        "## US-101: {{Story Title}}\n"
        "**As a** {{Role}},\n"
        "**I want** {{Action}},\n"
        "**So that** {{Business Value}}.\n\n"
        "* **Acceptance Criteria:**\n"
        " - Given {{context}}, when {{action}}, then {{result}}.\n"
        " - Given {{context}}, when {{action}}, then {{result}}.\n"
        " - Given {{context}}, when {{action}}, then {{result}}.\n\n"
        "## US-102: {{Story Title}}\n"
        "**As a** {{Role}},\n"
        "**I want** {{Action}},\n"
        "**So that** {{Business Value}}.\n\n"
        "* **Acceptance Criteria:**\n"
        " - Given {{context}}, when {{action}}, then {{result}}.\n"
        " - Given {{context}}, when {{action}}, then {{result}}.\n"
        " - Given {{context}}, when {{action}}, then {{result}}.\n\n"
        "Final Rules:\n"
        "- ONLY replace the text inside {{...}}. Do NOT remove the bold formatting.\n"
        "- Ensure your replacements are deeply detailed, highly technical, and strictly relevant to {project_name} and {industry}."
    ),
    "database_design": (
        "Generate the Database Design Suggestions section.\n\n"
        "Project Configuration:\n"
        "- Project Name: {project_name}\n"
        "- Industry Domain: {industry}\n"
        "- Target Core Modules: {features}\n"
        "- Scope and Context: {scope_details}\n"
        "- Detail Level (0.0 = concise, 1.0 = comprehensive): {creativity_level}\n\n"
        "CRITICAL INSTRUCTION: You MUST use the EXACT Markdown structure provided below. Do NOT remove any markdown headings (##), bold labels (**Label:**), or tables. ONLY replace the instructional text inside the curly braces {{...}} with your highly detailed, domain-specific content. KEEP the bold labels intact!\n\n"
        "## Core ERP Database Design Strategy\n"
        "* **Database Engine:** {{Suggest an engine e.g. PostgreSQL and explain why for this project.}}\n"
        "* **Audit Trail:** {{Explain audit strategy, soft deletes vs hard deletes.}}\n\n"
        "## Sample Physical/Logical Schema Structure\n"
        "{{table_name_1}}\n"
        " - id (UUID, PK)\n"
        " - {{column_name}} (VARCHAR)\n"
        " - {{column_name}} (NUMERIC)\n"
        " - {{column_name}} (TIMESTAMP)\n"
        " - {{column_name}} (UUID, FK)\n\n"
        "{{table_name_2}}\n"
        " - id (UUID, PK)\n"
        " - {{column_name}} (VARCHAR)\n"
        " - {{column_name}} (NUMERIC)\n"
        " - {{column_name}} (TIMESTAMP)\n"
        " - {{column_name}} (UUID, FK)\n\n"
        "Final Rules:\n"
        "- ONLY replace the text inside {{...}}. Do NOT remove the bold formatting.\n"
        "- Ensure your replacements are deeply detailed, highly technical, and strictly relevant to {project_name} and {industry}."
    ),
    "kpis": (
        "Generate the Key Performance Indicators (KPIs) section.\n\n"
        "Project Configuration:\n"
        "- Project Name: {project_name}\n"
        "- Industry Domain: {industry}\n"
        "- Target Core Modules: {features}\n"
        "- Scope and Context: {scope_details}\n"
        "- Detail Level (0.0 = concise, 1.0 = comprehensive): {creativity_level}\n\n"
        "CRITICAL INSTRUCTION: You MUST use the EXACT Markdown structure provided below. Do NOT remove any markdown headings (##), bold labels (**Label:**), or tables. ONLY replace the instructional text inside the curly braces {{...}} with your highly detailed, domain-specific content. KEEP the bold labels intact!\n\n"
        "# Key Performance Indicators (KPIs)\n"
        "Your ERP should measure both operational metrics (business success) and technical metrics (system performance).\n\n"
        "## Business Operations KPIs\n"
        "* **Financials:** {{List 2-3 detailed financial KPIs like DSO, DPO, etc.}}\n"
        "* **Operations:** {{List 2-3 detailed operational KPIs relevant to the selected modules.}}\n"
        "* **HR / Core:** {{List 2-3 detailed internal KPIs.}}\n\n"
        "## Technical & System KPIs\n"
        "* **User Adoption Rate:** {{Define the metric.}}\n"
        "* **Data Accuracy Rate:** {{Define the metric.}}\n"
        "* **System Uptime & Latency:** {{Define the metric.}}\n\n"
        "Final Rules:\n"
        "- ONLY replace the text inside {{...}}. Do NOT remove the bold formatting.\n"
        "- Ensure your replacements are deeply detailed, highly technical, and strictly relevant to {project_name} and {industry}."
    ),
    "workflow": (
        "Generate the Workflow Specifications section.\n\n"
        "Project Configuration:\n"
        "- Project Name: {project_name}\n"
        "- Industry Domain: {industry}\n"
        "- Target Core Modules: {features}\n"
        "- Scope and Context: {scope_details}\n"
        "- Detail Level (0.0 = concise, 1.0 = comprehensive): {creativity_level}\n\n"
        "CRITICAL INSTRUCTION: You MUST use the EXACT Markdown structure provided below. Do NOT remove any markdown headings (##), bold labels (**Label:**), or tables. ONLY replace the instructional text inside the curly braces {{...}} with your highly detailed, domain-specific content. KEEP the bold labels intact!\n\n"
        "# Workflows (BPMN 2.0 Framework)\n"
        "Workflows define how data moves across departments.\n\n"
        "## {{Generate a Realistic Process Name}} Cross-Functional Workflow\n"
        "1. **{{Actor/Dept 1}}:** {{Detailed Action}} -> {{Resulting System State}}\n"
        "2. **{{Actor/Dept 2}}:** {{Detailed Action}} -> {{Resulting System State}}\n"
        "3. **{{Actor/Dept 3}}:** {{Detailed Action}} -> {{Resulting System State}}\n"
        "4. **{{Actor/Dept 4}}:** {{Detailed Action}} -> {{Resulting System State}}\n"
        "5. **{{Actor/Dept 5}}:** {{Detailed Action}} -> {{Resulting System State}}\n\n"
        "Final Rules:\n"
        "- ONLY replace the text inside {{...}}. Do NOT remove the bold formatting.\n"
        "- Ensure your replacements are deeply detailed, highly technical, and strictly relevant to {project_name} and {industry}."
    ),
    "reports": (
        "Generate the Report Specifications section.\n\n"
        "Project Configuration:\n"
        "- Project Name: {project_name}\n"
        "- Industry Domain: {industry}\n"
        "- Target Core Modules: {features}\n"
        "- Scope and Context: {scope_details}\n"
        "- Detail Level (0.0 = concise, 1.0 = comprehensive): {creativity_level}\n\n"
        "CRITICAL INSTRUCTION: You MUST use the EXACT Markdown structure provided below. Do NOT remove any markdown headings (##), bold labels (**Label:**), or tables. ONLY replace the instructional text inside the curly braces {{...}} with your highly detailed, domain-specific content. KEEP the bold labels intact!\n\n"
        "# Reports Framework\n"
        "ERP reports must serve multiple organizational tiers: Operational, Tactical, and Strategic.\n\n"
        "| Report Name | Module | Target Audience | Key Data Fields Included | Frequency |\n"
        "|---|---|---|---|---|\n"
        "| {{Report Name}} | {{Module}} | {{Target Audience}} | {{Key Data Fields Included}} | {{Frequency}} |\n"
        "| {{Report Name}} | {{Module}} | {{Target Audience}} | {{Key Data Fields Included}} | {{Frequency}} |\n"
        "| {{Report Name}} | {{Module}} | {{Target Audience}} | {{Key Data Fields Included}} | {{Frequency}} |\n"
        "| {{Report Name}} | {{Module}} | {{Target Audience}} | {{Key Data Fields Included}} | {{Frequency}} |\n"
        "| {{Report Name}} | {{Module}} | {{Target Audience}} | {{Key Data Fields Included}} | {{Frequency}} |\n\n"
        "Final Rules:\n"
        "- ONLY replace the text inside {{...}}. Do NOT remove the bold formatting.\n"
        "- Ensure your replacements are deeply detailed, highly technical, and strictly relevant to {project_name} and {industry}."
    )
}


